# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test commits

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11.0.x, 11.0.3, 12, 13 ]

    steps:
    - uses: actions/checkout@v2

    - name: Set current branch name
    - uses: nelonoel/branch-name@v1.0.1
      env:
        BRANCH_NAME: ${BRANCH_NAME}

    - name: Override branch name if required
    - uses: nelonoel/branch-name@v1.0.1
      if: ${BRANCH_NAME} != "master" && ${BRANCH_NAME} != "development" && ${BRANCH_NAME} != "experimental"
      env:
        BRANCH_NAME: "development"
      run: echo "Running on ${BRANCH_NAME}"

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        java-package: jdk

    - name: Test build
      run: |
        mvn install
